dem/urls.py
from django.conf.urls import url
from dem import views

app_name = 'dem'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^interact_test/$', views.interact_test, name='interact_test'),
    url(r'^my_assignments/$', views.my_assignments, name='my_assignments'),
    url(r'^show_mission/(?P<mission_name_slug>[\w\-]+)/$',
        views.show_mission, name='show_mission'),
]

rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    #url(r'^register/$', views.register, name='register'),
    #url(r'^login/$', views.user_login, name="login"),
    url(r'^restricted/$', views.restricted, name='restricted'),
    #url(r'^logout/$', views.user_logout, name="logout"),
]

twd/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rango/', include('rango.urls')),
    url(r'^dem/', include('dem.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'User Profiles'

rango/forms.py
from django import forms
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',  )

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = {'username', 'email', 'password'}

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = {'website', 'picture'}

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime

def index(request):
    #request.session.set_test_cookie()

    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context_dict)
    return response

def about(request):
    # if request.session.test_cookie_worked():
    #     print("THE TEST COOKIE IS WORKING!")
    #     request.session.delete_test_cookie()
    visitor_cookie_handler(request)
    visits = request.session['visits']

    context_dict = {'h2': "I am an h2!", 'visits': visits}
    return render(request, 'rango/about.html', context_dict)

def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None
    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    context_dict = {'form':form, 'category':category}
    return render(request, 'rango/add_page.html', context_dict)

# def register(request):
#     registered = False
#
#     if request.method == "POST":
#         user_form = UserForm(data=request.POST)
#         profile_form = UserProfileForm(data=request.POST)
#
#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()
#
#             profile = profile_form.save(commit=False)
#             profile.user = user
#             if 'picture' in request.FILES:
#                 profile.picture = request.FILES['picture']
#             profile.save()
#
#             registered = True
#         else:
#             print(user_form.errors, profile_form.errors)
#     else:
#         user_form = UserForm()
#         profile_form = UserProfileForm()
#
#     return render(request,
#                   'rango/register.html',
#                   {'user_form': user_form,
#                    'profile_form': profile_form,
#                     'registered': registered})
#
# def user_login(request):
#     if request.method == "POST":
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(username = username, password = password)
#         if user:
#             if user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('rango:index'))
#             else:
#                 return HttpResponse("Your Rango account is disabled.")
#         else:
#             print("Invalid login details: {0}, {1}".format(username, password))
#             return HttpResponse("Invalid login details supplied.")
#     else:
#         return render(request, 'rango/login.html', {})
#
# def user_logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse('rango:index'))

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    print("" + cookie + ": " + str(val))
    return val

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
  About
{% endblock %}

{% block body_block %}
  <h1>This is the About page!</h1>
  <h2>{{ h2 }}</h2>
  <p>Why are we showing this lizard picture so much?</p>
  <p>Visits: {{ visits }}<p>
  <img src="/media/rango.jpg" alt="The Rango pic again!" />
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Add Category
{% endblock %}

{% block body_block %}
  <form role="form" id="category_form" method="post" action="/rango/add_category/">
    <h2 class="form-signin-heading"> Add a Category</h2>
    {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br/>
        {{ field }}<br/>
      {% endfor %}
    <br/>
    <button class="btn btn-primary" type="submit" name="submit">Add Category</button>
  </form>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}Add Page{% endblock %}
{% block body_block %}
  {% if category %}
    <form role="form" id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
      <h2 class="form-signin-heading"> Add a Page to
        <a href="/rango/category/{{category.slug}}/"> {{ category.name }}</a></h2>
        {% csrf_token %}
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br/>
            {{ field }}<br/>
          {% endfor %}
        <br/>
        <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
      </form>
    {% else %}
      <p>This is category does not exist.</p>
    {% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
  <head lang="en">
    <meta charset="UTF-8" />
    <title>
      Rango -
      {% block title_block %}
        How to Tango with Django!
      {% endblock %}
    </title>
  </head>
  <body>

    <div>
      {% block sidebar_block %}
        {% get_category_list category %}
      {% endblock %}
    </div>

    <div>
      {% block body_block %}
      {% endblock %}
    </div>
    <hr />
    <div>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
          <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
        {% else %}
          <li><a href="{% url 'auth_login' %}">Sign In</a></li>
          <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
        {% endif %}
          <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
          <li><a href="{% url 'rango:about' %}">About</a></li>
          <li><a href="{% url 'rango:index' %}">Index</a></li>
      </ul>
    </div>
  </body>

templates/rango/bootstrap_base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
      Rango - {% block title %}How to Tango with Django!{% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"
    rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
      <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Rango</a>
      <div id="navbar">
        <nav class="nav navbar-nav pull-xs-left">
          <a class="nav-item nav-link" href="{% url 'rango:index' %}">Home</a>
          <a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
            <a class="nav-item nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'registration_register' %}">Register Here</a>
            <a class="nav-item nav-link" href="{% url 'auth_login' %}">Login</a>
          {% endif %}
        </nav>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% block sidebar_block %}
            {% get_category_list category %}
          {% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          {% block body_block %}{% endblock %}
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.j\s"></script>
  </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {{category.name}}
{% endblock %}

{% block body_block %}
  {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}
      <ul>
        {% for page in pages %}
          <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <strong>No pages currently in category.</strong>
    {% endif %}
    <a href="/rango/category/{{category.slug}}/add_page/">Add Page</a> <br/>
  {% else %}
    The specified category does not exist!
  {% endif %}
{% endblock %}

templates/rango/cats.html
<ul>
  {% if cats %}
    {% for c in cats %}
      {% if c == act_cat %}
        <li>
          <strong>
            <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
          </strong>
        </li>
      {% else %}
      <li>
        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
      </li>
      {% endif %}
    {% endfor %}
  {% else %}
    <li> <strong>There are no categories present.</strong></li>
  {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
  Index
{% endblock %}
{% block body_block %}
  <div class="jumbotron">
    <h1 class="display-3">Rango says...</h1>
    {% if user.is_authenticated %}
      <h1>hey there {{ user.username }}!</h1>
    {% else %}
      <h1>hey there partner! </h1>
    {% endif %}
  </div>
  <div class="row marketing">
    <div class="col-lg-6">
      <h4>Most Liked Categories</h4>
      <p>
        {% if categories %}
          <ul class="list-group">
            {% for category in categories %}
              <li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
              {% endfor %}
            </ul>
        {% else %}
          <strong>There are no categories present.</strong>
        {% endif %}
      </p>
    </div>
    <div class="col-lg-6">
      <h4>Most Viewed Pages</h4>
      <p>
        {% if pages %}
          <ul class="list-group">
            {% for page in pages %}
              <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
          </ul>
        {% else %}
          <strong>There are no categories present.</strong>
        {% endif %}
      </p>
    </div>
  </div>
  <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  login
{% endblock %}

{% block body_block %}
  <link href="http://v4-alpha.getbootstrap.com/examples/signin/signin.css" rel="stylesheet">
  <div class="jumbotron">
    <h1 class="display-3">Login</h1>
  </div>
  <form class="form-signin" role="form" method="post" action=".">
    {% csrf_token %}
    <h2 class="form-signin-heading">Please sign in</h2>
    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" />Sign in</button>
  </form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Register
{% endblock %}

{% block body_block %}
  <h1>About Page</h1>
  {% if registered %}
    Rango says: <strong>thank you for registering!</strong>
    <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
  {% else %}
    Rango says: <strong>register here!</strong><br />
    <form id="user_form" method="post" action="{% url 'rango:register' %}"
    enctype="multipart/form-data">

      {% csrf_token %}

      <!-- Display each form -->
      {{ user_form.as_p }}
      {{ profile_form.as_p }}

      <!-- Provide a button to click to submit the form. -->
      <input type="submit" name="submit" value="Register" />
    </form>
  {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Restricted Page
{% endblock %}

{% block body_block %}
  <h1>This is a restricted page!</h1>
{% endblock %}