dem/urls.py
from django.conf.urls import url
from dem import views

app_name = 'dem'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^interact_test/$', views.interact_test, name='interact_test'),
    url(r'^my_assignments/$', views.my_assignments, name='my_assignments'),
    url(r'^show_mission/(?P<mission_name_slug>[\w\-]+)/$',
        views.show_mission, name='show_mission'),
]

twd/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rango/', include('rango.urls')),
    url(r'^dem/', include('dem.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

dem/models.py
from django.db import models
from django.contrib.auth.models import User
from localflavor.us.models import USStateField
from django.template.defaultfilters import slugify
from datetime import datetime

class DemUser(models.Model):
    user = models.OneToOneField(User)
    state = USStateField(null=True, blank=True)
    monies = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Dem Users'

class Reward(models.Model):
    monies = models.IntegerField(default=100)
    title = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.title

class Proposal(models.Model):
    title = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    author = models.ForeignKey(DemUser)
    endorsements = models.IntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.date_created = datetime.now()
        super(Proposal, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Proposals'

class Mission(models.Model):
    title = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(unique=True)
    creator = models.ForeignKey(DemUser)
    date_created = models.DateTimeField(auto_now_add=True)
    #lat_coord = models.DecimalField(max_digits=9, decimal_places=6)
    #lng_coord = models.DecimalField(max_digits=9, decimal_places=6)
    description = models.TextField(default="No Description Available")
    #reward = models.ForeignKey(Reward)
    def __str__(self):
        return self.title

class Assignment(models.Model):
    assignee = models.ForeignKey(DemUser)
    mission = models.ForeignKey(Mission)
    reward = models.ForeignKey(Reward)
    lat_coord = models.DecimalField(max_digits=9, decimal_places=6)
    lng_coord = models.DecimalField(max_digits=9, decimal_places=6)

    def __str__(self):
        return self.mission.title

dem/forms.py
from django import forms
from dem.models import DemUser
from django.contrib.auth.models import User
from localflavor.us.models import USStateField

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = {'username', 'email', 'password'}

class DemUserForm(forms.ModelForm):
    state = USStateField(null=True, blank=True)

    class Meta:
        model = DemUser
        fields = {'state'}

dem/views.py
from django.shortcuts import render
from dem.models import DemUser, Assignment, Mission
from dem.forms import DemUserForm, UserForm
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

def index(request):
    context_dict = {}
    return render(request, 'dem/index.html', context_dict)

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        dem_user_form = DemUserForm(data=request.POST)

        if user_form.is_valid() and dem_user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            dem_user = dem_user_form.save(commit=False)
            dem_user.user = user
            dem_user.save()
            registered = True
        else:
            print(user_form.errors, dem_user_form.errors)
    else:
        user_form = UserForm()
        dem_user_form = DemUserForm()
    return render(request,
                  'dem/register.html',
                  {'user_form': user_form,
                   'dem_user_form': dem_user_form,
                    'registered': registered})

@login_required
def my_assignments(request):
    context_dict = {}
    dem_user = DemUser.objects.get(user=request.user)
    if request.user.is_active:
        context_dict['assignments'] = get_user_assignments(dem_user)
        return render(request, 'dem/my_assignments.html', context_dict)
    else:
        return HttpResponse("You are not logged in!")

def show_mission(request, mission_name_slug):
    context_dict = {}
    try:
        mission = Mission.objects.get(slug=mission_name_slug)
        context_dict['mission'] = mission
    except Mission.DoesNotExist:
        context_dict['mission'] = None
    return render(request, 'dem/mission.html', context_dict)

# def assignment(request):
#     if request.method == "POST":
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(username=username, password=password)
#
#         if user:
#             if user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('dem:index'))
#             else:
#                 return HttpResponse('Your Dem account is not active.')
#         else:
#             print('Invalid login details {0}, {1}'.format(username, password))
#             return HttpResponse("Invalid login details supplied")
#     else:
#         return render(request, 'dem/login.html', {})

# def dem_login(request):
#     if request.method == "POST":
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(username=username, password=password)
#
#         if user:
#             if user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('dem:index'))
#             else:
#                 return HttpResponse('Your Dem account is not active.')
#         else:
#             print('Invalid login details {0}, {1}'.format(username, password))
#             return HttpResponse("Invalid login details supplied")
#     else:
#         return render(request, 'dem/login.html', {})

def get_user_assignments(dem_user):
        return Assignment.objects.filter(assignee=dem_user)

def interact_test(request):
    return render(request, 'dem/interact_test.html', {})

templates/dem/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head lang="en">
    <meta charset="UTF-8" />
    <title>
      Dem -
      {% block title_block %}
        It's Dem time!
      {% endblock %}
    </title>
  </head>
  <body>

    <div>
      {% block sidebar_block %}
      {% endblock %}
    </div>

    <div>
      {% block body_block %}
      {% endblock %}
    </div>
    <hr />
    <div>
      <ul>
        <li><a href="{% url 'dem:index' %}">Home</li>
        {% if not user.is_authenticated %}
          <li><a href="{% url 'auth_login' %}?next=/dem/">Login</li>
          <li><a href="{% url 'dem:register' %}">Register</a></li>
        {% else %}
          <li><a href="{% url 'auth_logout' %}?next=/dem/">Logout</a></li>
          <li><a href="{% url 'dem:my_assignments' %}">My Assignments</a></li>
        {% endif %}
      </ul>
    </div>
  </body>

templates/dem/index.html
{% extends 'dem/base.html' %}
{% load staticfiles %}

{% block body_block %}
  <h1>Welcome to Dem {{ user.username }}!</h1>
{% endblock %}

templates/dem/interact_test.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <body>
    <div id="grid-snap">
      Dragging is constrained to the corners of a grid
    </div>
  </body>

  <link rel="stylesheet" type="text/css" href="{% static "css/interact_test_style.css" %}">
  <script src="{% static "js/interact.min.js" %}"></script>
  <script src="{% static "js/grid_test.js" %}"></script>
</html>

templates/dem/login.html
{% extends 'dem/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Login
{% endblock %}

{% block body_block %}
  <h1>Login to Dem!</h1>
  <form id="login_form" method="post" action="{% url 'dem:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="text" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
  </form>
{% endblock %}

templates/dem/mission.html
{% extends 'dem/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {{mission.title}}
{% endblock %}

{% block body_block %}
  {% if mission %}
    <table border="1" cellpadding="5" cellspacing="5">
      <tr>
        <th>Title</th>
        <th>Creator</th>
        <th>Date Created</th>
        <th>Description</th>
      </tr>
      <tr>
        <td>{{mission.title}}</td>
        <td>{{mission.creator}}</td>
        <td>{{mission.date_created}}</td>
        <td>{{mission.description}}</td>
      </tr>
    </table>
  {% else %}
    The specified mission does not exist!
  {% endif %}
{% endblock %}

templates/dem/my_assignments.html
{% extends 'dem/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {{ user.username }} : Assignments
{% endblock %}

{% block body_block %}
<h1>{{ user.username }}'s Assignments</h1>
  {% if assignments %}
    <table border="1" cellpadding="5" cellspacing="5">
      <tr>
        <th>Title</th>
        <th>Latitude</th>
        <th>Longitude</th>
      </tr>
      {% for assignment in assignments %}
        <tr>
          <td><a href="{% url 'dem:show_mission' assignment.mission.slug %}">{{assignment.mission.title}}</a></td>
          <td>{{assignment.lat_coord}}</td>
          <td>{{assignment.lng_coord}}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <strong>No assignments for you.</strong>
  {% endif %}
{% endblock %}

templates/dem/register.html
{% extends 'dem/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Register at Dem
{% endblock %}

{% block body_block %}
  <h1>Time to Register!</h1>
  {% if registered %}
    <strong>Thank you for registering!</strong>
    <a href="{% url 'dem:index' %}">Return to the homepage.</a><br />
  {% else %}
    <strong>Register here!</strong><br />
    <form id=dem_user_form method="post" action="{% url 'dem:register' %}" enctype="multipart/form-data">
      {% csrf_token %}
      {{user_form.as_p}}
      {{dem_user_form.as_p}}
      <input type="submit" name="submit" value="Register">
    </form>
  {% endif %}
{% endblock %}